name: Deployment

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DATO_WEBHOOK_ID: ${{ secrets.DATO_WEBHOOK_ID }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Send success status
        if: success()
        run: |
          curl -n -X POST https://webhooks.datocms.com/${{ env.DATO_WEBHOOK_ID }}/deploy-results \
            -H 'Content-Type: application/json' \
            -d '{ "status": "success" }'
      - name: Send failure status
        if: failure()
        run: |
          curl -n -X POST https://webhooks.datocms.com/${{ env.DATO_WEBHOOK_ID }}/deploy-results \
            -H 'Content-Type: application/json' \
            -d '{ "status": "error" }'
