name: Deployment

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  Update-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update production
        run: |
          git checkout production
          git merge $GITHUB_REF
          git push origin production

  Deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy to production
        run: vercel --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Send status
        if: success()
        run: |
          curl -n -X POST https://webhooks.datocms.com/XOCxELkDWJ/deploy-results \
            -H 'Content-Type: application/json' \
            -d '{ "status": "success" }'
      - name: Send status
        if: failure()
        run: |
          curl -n -X POST https://webhooks.datocms.com/XOCxELkDWJ/deploy-results \
            -H 'Content-Type: application/json' \
            -d '{ "status": "error" }'
