name: Preview Deployment

on:
  pull_request:
    branches-ignore:
      - main
      - main/**
      - gh-readonly-queue/**
  push:
    branches-ignore:
      - main
      - main/**
      - gh-readonly-queue/**
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token $VERCEL_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token $VERCEL_TOKEN
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token $VERCEL_TOKEN
