name: Schema Check

on:
  workflow_dispatch:

jobs:
  Schema-check:
    runs-on: ubuntu-latest
    environment: apollo
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      DATOCMS_ACCESS_TOKEN: ${{ secrets.DATOCMS_ACCESS_TOKEN }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.19.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Validating subgraph schema changes
        if: ${{ env.DATOCMS_ACCESS_TOKEN != '' }}
        run: |
          rover graph introspect https://graphql.datocms.com --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
            | rover subgraph check crea-orkest-p7nmyh@main \
            --schema - --name datocms
      - name: Downloading datocms schema
        if: ${{ env.DATOCMS_ACCESS_TOKEN != '' }}
        run: |
          rover graph introspect https://graphql.datocms.com --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
          > ./src/graphql/generated/datocms.graphql
      - name: Publishing datocms schema
        if: ${{ env.APOLLO_KEY != '' }}
        run: |
          rover subgraph publish crea-orkest-p7nmyh@main --name datocms --schema ./src/graphql/generated/datocms.graphql
