name: Update production

on:
  push:
    tags:
      - v*

jobs:
  Update-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Update
        run: |
          git checkout production
          git merge $GITHUB_REF
          git push origin production
